export const ARTICLES_DATA = [
    {
        id: 1,
        author: "Le võ dang khoa ly thanh nhat quang phuc tran thanh",
        time: "2025-11-20 09:30:00",
        title: "Your portfolio is stopping you from getting that job",
        content: "An intense way to learn about the process and practice your designs skills — My 1st hackathon Hackathons have been on my mind since I heard it was a good way to gain experience as a junior UX designer. As my portfolio...",
        assets: ["https://placehold.co/400x400/1e293b/FFF?text=Portfolio"],
        tags: ["Career", "Design"],
    },
    {
        id: 2,
        author: "Amit Das",
        time: "2025-11-19 14:20:15",
        title: "Melody mobile app: a UI UX case study",
        content: "Music is something that everyone loves. But how do we design an app that not only plays music but understands the user's mood? Here is my journey of designing the Melody App...",
        assets: ["https://placehold.co/400x400/3b82f6/FFF?text=Mobile+App"],
        tags: ["UI/UX Design", "Case Study"],
    },
    {
        id: 3,
        author: "Sarah Jenkins",
        time: "2025-11-18 10:15:00",
        title: "Why Redux Toolkit is a game changer for React Developers",
        content: "Gone are the days of complex boilerplate code. Redux Toolkit simplifies state management in React applications effectively. Let's dive into createSlice and createAsyncThunk...",
        assets: ["https://placehold.co/400x400/7c3aed/FFF?text=Redux"],
        tags: ["React", "Development"],
    },
    {
        id: 4,
        author: "David Nguyen",
        time: "2025-11-17 08:45:00",
        title: "The Art of Minimalist Web Design",
        content: "Whitespace is not empty space. It is an active element of design. Learn how to use negative space to guide user attention and improve readability in your next web project...",
        assets: ["https://placehold.co/400x400/10b981/FFF?text=Minimalism"],
        tags: ["Design", "Web"],
    },
    {
        id: 5,
        author: "Emily Watson",
        time: "2025-11-16 16:50:00",
        title: "10 Tips to Ace Your Frontend Interview",
        content: "Technical skills are important, but soft skills and problem-solving approaches matter just as much. Here are the top 10 things interviewers look for in a Senior Frontend Developer...",
        assets: ["https://placehold.co/400x400/f59e0b/FFF?text=Interview"],
        tags: ["Career", "Tips"],
    },
    {
        id: 6,
        author: "Michael Chen",
        time: "2025-11-15 11:00:00",
        title: "Understanding Next.js 15 Server Actions",
        content: "Next.js 15 introduces powerful Server Actions that allow you to mutate data directly from your components without creating API routes. Is this the future of full-stack React?",
        assets: ["https://placehold.co/400x400/000000/FFF?text=Next.js"],
        tags: ["Technology", "Next.js"],
    },
    {
        id: 7,
        author: "Jessica Lee",
        time: "2025-11-14 09:10:00",
        title: "Color Theory for Developers: A Crash Course",
        content: "You don't need to be a designer to pick good colors. Understanding complementary, analogous, and monochromatic schemes can help you build better-looking UIs...",
        assets: ["https://placehold.co/400x400/ec4899/FFF?text=Colors"],
        tags: ["Design", "Tutorial"],
    },
    {
        id: 8,
        author: "Robert Fox",
        time: "2025-11-13 13:25:00",
        title: "My setup for maximum productivity in 2025",
        content: "From VS Code extensions to desk setup. Here is how I configure my environment to stay focused and code faster without burning out...",
        assets: ["https://placehold.co/400x400/6366f1/FFF?text=Setup"],
        tags: ["Productivity", "Lifestyle"],
    },
];